FROM jwilder/nginx-proxy:alpine


ENV ACME_BUILD_DATE=2019-06-27
ENV AUTO_UPGRADE=1
ENV LE_WORKING_DIR=/acme.sh
ENV LE_CONFIG_HOME=/acmecerts
RUN wget -O- https://get.acme.sh | sh && crontab -l | sed 's#> /dev/null##' | crontab -

VOLUME ["/acmecerts"]
EXPOSE 443

COPY ./* /app/

RUN chmod +x /app/updatessl.sh

RUN mkdir -p /etc/nginx/stream.d

VOLUME ["/etc/nginx/stream.d"]

